title: ES Conference Deadlines
description: Countdowns to top CV/NLP/ML/Robotics/AI/ES conference deadlines
author: Abhishek Das

domain: "atreus.informatik.uni-tuebingen.de"
baseurl: "/es-deadlines"

twitter_username: 
twitter_hashtag: embeddedsystems
github_username: ekut-es
github_repo: es-deadlines

markdown: kramdown
ga_id: 

include: ['_pages']
