title: AI Conference Deadlines # (Maintained by @abhshkdz)
remark: CV/MIC-oriented

# email: wangchangmiao@cuhk.edu.cn
description: Countdowns to top CV/ML/MIC/NLP/Robotics/Special_Issue conference deadlines
author: Changmiao Wang

domain: "jiandanjinxin.github.io"
baseurl: "/cv-ml-mic_deadlines"

#twitter_username: abhshkdz
#twitter_hashtag: machinelearning
github_username: jiandanjinxin
github_repo: cv-ml-mic_deadlines

markdown: kramdown
#ga_id: UA-36274081-2

include: ['_pages']
