title: AI Conference Deadlines # (Maintained by @abhshkdz)
# email: abhshkdz@vt.edu
description: Countdowns to top CV/NLP/ML/Robotics/AI conference deadlines.

baseurl: "https://rymc.github.io/ai-deadlines/"
twitter_username: abhshkdz
github_username: abhshkdz

markdown: kramdown
ga_id: UA-36274081-2
